def remote = [:]
remote.name = 'devadmin'
remote.host = '192.168.100.123'
remote.allowAnyHosts = true

pipeline {
    agent any
    environment {
        DEV_CREDENTIALS = credentials('devadmin')
    }

    stages {
        stage('Reading Environment Variables from .env file') {
            steps {
                script {
                    def props = readProperties file: '.env'

                    props.each {
                        env."${it.key}" = "${it.value}"
                    }
                }
                echo "${T_PASS}"
            }
        }
        stage('Deploying Docker Compose to Staging Server') {
            steps {
                script {
                    remote.user = env.DEV_CREDENTIALS_USR
                    remote.password = env.DEV_CREDENTIALS_PSW
                }
                sshCommand (remote: remote, command: """
                    cd ~/projects/deploy-nib-online/admin-portal
                    echo ${T_PASS} | sudo -S bash docker compose down 
                    echo ${T_PASS} | sudo -S bash docker compose up -d
                    """
                    )
                }
            }
        }
    }